spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:vtsign/git-config-server.git
          search-paths:
            - auth-service
            - user-service
            - document-service
            - notification-service
            - api-gateway
            - registry-service
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://vtsign.tech:8761/eureka/