server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://vtsign.tech:8761/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GH_REPO}
          username: ${GH_USERNAME}
          password: ${GH_PASSWORD}
          search-paths:
            - auth-service
            - user-service
            - document-service
            - notification-service
            - api-gateway
            - registry-service